mi_bundle:
    resource: "@MiBundle/Resources/config/routing.yml"
    prefix:   /MiBundle/

rutas_bundle:
    resource: "@AppBundle/Resources/Config/routing.yml"
    prefix: /testing/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
