MiBundle\Entity\Curso:
  properties:
    titulo:
      - NotBlank: {message: "El titulo no puede estar vacio"}
      - Length:
        min: 2
        minMessage: "El titulo debe tener mas de dos caracteres"
    descripcion:
      - NotBlank: {message: "La descripcion ni puede estar vacia"}
    precio:
      - Type:
          type: numeric
          message: "El precio debe ser numerico"
